sudo: required
dist: trusty
language: cpp

matrix:
  include:
  
  #
  # Monero release-all
  #
  - os: linux
    compiler:
      - gcc
      - clang
    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - doxygen
          - g++
          - gcc
          - clang
          - graphviz
          - libdb++-dev
          - libdb-dev
          - libgtest-dev
          - libminiupnpc-dev
          - libssl-dev
          - libssl1.0.0
          - libunbound-dev
          - libunwind8-dev
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo add-apt-repository -y ppa:kojoley/boost
      - sudo apt-get -q update
    install:
      - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}1.58{-dev,.0}
    script:
      - make -j2 && HAVE_DOT=YES doxygen Doxyfile
    
    - os: osx
    osx_image: xcode7.3
    compiler:
      - gcc
      - clang
    before_install:
      # update brew.
      - brew update
    install:
      # Install deps.
      - brew install gcc@5 cmake pkg-config boost@1.59 boost git openssl@1.1 zmqpp zmq unbound libsodium miniupnpc libunwind-headers xz readline ldns expat doxygen graphviz

    script:
      # compile.
      - make

    #notifications:
    #  email: false
    #  irc:
    #    on_success: change
    #    on_failure: change
    #    channels:
    #      - "chat.freenode.net#monero-dev"
    #    nick: monero
    #    template:
    #      - "%{result} | %{repository}#%{build_number} (%{commit} : %{author}) | Build details : %{build_url}"
