# name: mynt-blockchain
version:  "0.11.2"
summary: Mynt Daemon, the "Mynt Daemon" snap
  description: |
    Mynt is a private, secure, untraceable, decentralised digital currency.
    You are your bank, you control your funds, and nobody can trace your transfers
    unless you allow them to do so.
grade: stable
confinement: strict

apps:
  myntd:
    command: myntd
    plugs: [network-bind,network,home]
parts:
  gnu-mynt:
    plugin: make
    source: https://github.com/mynt-project/Mynt/archive/0.11.0.2.tar.gz
    install: | 
        make && mkdir ~/mynt && cp * ~/mynt
    build-packages:
        - gcc 
        - g++
        - cmake
        - libboost-all-dev 
        - libdb5.3-dev
        - libunbound-dev
        - libunwind8-dev
        - libssl-dev
