  # After registering a name on build.snapcraft.io, commit an uncommented line:
  # name: your-registered-name
  # name: mynt
  version: "0.11.2"
  summary: Mynt Daemon
  description: |
    Mynt is a private, secure, untraceable, decentralised digital currency.
    You are your bank, you control your funds, and nobody can trace your transfers
    unless you allow them to do so.
  grade: devel # must be 'stable' to release into candidate/stable channels
  # confinement: devmode # use 'strict' once you have the right plugs and slots
  # confinement: strict

apps:
    myntd:
      command: |
          myntd 
      plugs: [network-bind,network,home]
    monero-wallet-cli:
      command: |
          mynt-wallet-cli --log-file ${SNAP_USER_DATA}
      plugs: [network,home]
    myntnote-wallet-rpc:
        command: |
          mynt-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs: [network-bind,network,home]

parts:
    myntd:
      plugin: make
      source: https://github.com/mynt-project/Mynt/archive/0.11.0.2.tar.gz
      install: | 
        mkdir ~/mynt && mv * ~/mynt && cd ~/mynt && make
      build-packages:
        - gcc 
        - g++
        - cmake
        - libboost-all-dev 
        - libdb5.3-dev
        - libunbound-dev
        - libunwind8-dev
        - libssl-dev
